# Generated by Django 5.0.7 on 2024-08-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kigali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_location', models.CharField(max_length=3)),
                ('city_population', models.IntegerField()),
            ],
        ),
    ]
